version: "3.9"

services:
  django_web:
    build: .
    command: >
      sh -c "python weather/manage.py migrate &&
             python weather/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - ./.env